### ISSUE TITLE
Rendering issue while using map

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#10]
## Below code works but can't use since its kind of hardcoding

```
{
  data.employeeList ? (
    <>
      <DataView list={data.employeeList[0]} />
      <PageBreak />
      <DataView list={data.employeeList[1]} />
      <PageBreak />
      <DataView list={data.employeeList[2]} />
    </>
  ) : null
}
```

## Using map it works but It displays data in single page and **PageBreak** doesn't happen

```
data.employeeList.map((subList, index) => (
  <React.Fragment key={index} >
    <DataView list={subList} />
    <PageBreak />
  </React.Fragment>
))
```

**Comment by PejmanNik** [comment]
Thank you for reporting it, The page break doesn't work in the Fragment components. It will be fixed in the next version but until i release it, you can replace the Fragment with any Html component

**Comment by sharathm89** [comment]
> Thank you for reporting it, The page break doesn't work in the Fragment components. It will be fixed in the next version but until i release it, you can replace the Fragment with any Html component

Sure let me check it
