### ISSUE TITLE
Version 0.3.0 Error: this version of React is not supported

### ISSUE THREAD

**Issue by nosykretts** [PejmanNik/jikji#12]
Using latest Next.js

<img width="971" alt="Screenshot 2023-07-04 at 15 36 17" src="https://github.com/PejmanNik/jikji/assets/2125103/b520d33a-0d0c-451d-8b39-8b72ca68b825">

├── @fontsource/ibm-plex-sans@5.0.3
├── @jikji/react@0.3.0
├── @types/node@20.3.3
├── @types/react-dom@18.2.6
├── @types/react@18.2.14
├── autoprefixer@10.4.14
├── eslint-config-next@13.4.7
├── eslint@8.44.0
├── next@13.4.7
├── postcss@8.4.24
├── react-dom@18.2.0
├── react-hook-form@7.45.1
├── react@18.2.0
├── recoil@0.7.7
├── tailwindcss@3.3.2
└── typescript@5.1.6

**Comment by PejmanNik** [comment]
Please update to Version 0.3.1
