### ISSUE TITLE
Last row from table displays partial information in page and remaining in next page

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#15]
Last row from table displays partial information in 1 page and other row details in next page.

Opening the website on different screen resolutions also matters. (Below screenshots are from 16 inch screen)

Here is the github repo link which demonstrates table row issue.  (checkout the readme file)

[Repo Link](https://github.com/sharathm89/report-app)

Prepared some sample code in the above repo.  Below are the direct links for js, css files.

**Basic CSS for table styling**
[CSS](https://github.com/sharathm89/report-app/blob/master/src/App.css)

**Header, Footer required to reproduce the issue**
[App.js](https://github.com/sharathm89/report-app/blob/master/src/App.js)

**Table Display**
[Table](https://github.com/sharathm89/report-app/blob/master/src/views/table/index.js)

**Image 1**

<img width="922" alt="Screenshot 2023-07-12 at 12 08 21 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/e15cd0ae-2781-4ca9-aaf2-4cb4431cab46">

**Image 2**

<img width="961" alt="Screenshot 2023-07-12 at 12 08 27 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/dd13ba5b-750f-4f0c-8051-e76c4a2c962b">

**Image 3**

<img width="981" alt="Screenshot 2023-07-12 at 12 08 35 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/18e1e6cb-7099-4ba2-abbb-0f8fd9e19adf">

**Comment by sharathm89** [comment]
@PejmanNik  this is the only issue which is blocking the report since the output looks doesn't look good.  

Lmk if you need any other details.

**Comment by sharathm89** [comment]
Any update on this ticket...

**Comment by sharathm89** [comment]
@PejmanNik  Sample code setup is done in codesandbox... 

Check the end of each page where partial information is displayed and remaining in next page. 

Please check the below link.

https://codesandbox.io/s/report-web-app-mm4l5l?file=/src/views/table/index.js

**Comment by PejmanNik** [comment]
Thank you, Yes I can reproduce the issue, it is in my plan to fix but I can't provide any ETA right now
