### ISSUE TITLE
usePageInfo doesn't work in the PageContent

### ISSUE THREAD

**Issue by PejmanNik** [PejmanNik/jikji#16]
usePageInfo hook returns the default value when it used inside the PageContent

https://codesandbox.io/s/jikji-test-page-number-8cvsq3

**Comment by sharathm89** [comment]
Any update on this ticket ...

**Comment by PejmanNik** [comment]
No, against my first guess, it is not easy to fix as at the time of splitting components in page content the usePageInfo hook returned 0, and the component converted to a Fragment

as a workaround for now, you can put your logic in a separate component (that return null, render nothing) and uses usePageInfo inside it, then wrap it in with Layout component (with disableSnapshot)
```js
 <Layout disableSnapshot>
     <PageNumberLogic />
 </Layout>
```

**Comment by sharathm89** [comment]
> 

@PejmanNik  sorry I didn't follow you..     

Is it possible create a sample codesandbox.

**Comment by PejmanNik** [comment]
https://codesandbox.io/s/jikji-test-page-number-forked-mggzy2?file=/src/App.tsx

**Comment by sharathm89** [comment]
Thanks... Its working.
