### ISSUE TITLE
Feature - A4 Landscape Format

### ISSUE THREAD

**Issue by RitschAlex** [PejmanNik/jikji#22]
Would it be possible to add A4 Landscape dimensions. 

`A4_Landscape: { height: '210mm', width: '296.8mm' }`

I think that A4 Landscape is next to A4 one of the most used pdf format and would be an great add to the library.

**Comment by PejmanNik** [comment]
There is a `PageOrientation` prop in the [Section](https://jikji.xyz/docs/components/section/#props) that you can use, also the page size is a simple object, you can use any dimension/size like: `{height: string; width: string}`
