### ISSUE TITLE
Pass parameter in Route

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#25]
Passing a path parameter doesn't seem to work.

For ex: Based on id it needs to fetch different kind of data so in that case passing as path parameter would be easy.

Lmk if there is some other way to achieve it.

**Sample Code**

```
const DefaultApp = () => (
  <Container>
    <h2>Report App</h2>
    <br />
    <a href="invoice/67">67 Test</a>
  </Container>
);

const App = () => (
  <BrowserRouter>
    <Route path="invoice/:id" component={Invoice} />
    <Route path="" component={DefaultApp} isDefault />
  </BrowserRouter>
);
```

https://github.com/PejmanNik/jikji/assets/17666778/eac4c5fe-482f-4109-b676-0ce2d2e871ff

**Comment by PejmanNik** [comment]
The router component is very simple and just exists to cover the basic usage without a third-party library, as this library attempt to handle reports I don't want to focus on routing, there are several advanced router components for React you can use. for instance [react-router](https://github.com/remix-run/react-router)

**Comment by sharathm89** [comment]
> The router component is very simple and just exists to cover the basic usage without a third-party library, as this library attempt to handle reports I don't want to focus on routing, there are several advanced router components for React you can use. for instance [react-router](https://github.com/remix-run/react-router)

Thanks

**Comment by PejmanNik** [comment]
No problem 👍
