### ISSUE TITLE
Graph isn't displayed after PDF is generated.

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#31]
The below screenshot shows graph rendered in browser. 

![Screenshot 2024-01-21 at 11 39 13 PM](https://github.com/PejmanNik/jikji/assets/17666778/0a89c4d0-06d1-413d-96c0-435141349ca1)

The below 2 sample screenshots are from the PDF generated through code.
![Screenshot 2024-01-21 at 11 39 50 PM](https://github.com/PejmanNik/jikji/assets/17666778/8dadb1dc-ea96-489f-95e8-0bc63ff52a84)

![Screenshot 2024-01-21 at 11 40 05 PM](https://github.com/PejmanNik/jikji/assets/17666778/aa155c10-8b63-4bf0-8b08-16b8210ddd16)

**JS Code**

Sending the pdfbuffer as an attachment in the mail 

```
       const browser = await puppeteer.launch({
		args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
		headless: "new",
	});

	try {
		const host = "http://localhost:3004";
		const path = `/mis-report`;
		const obj = ReportBuilder.browser(browser).remoteHost(host);

		await obj.report(path).pdf().build();

		return obj.result.get(path).pdf;
	} finally {
		await browser.close();
	}
```

If its returned to the browser directly even then it doesn't display the graph.

```
res.set({ "Content-Type": "application/pdf", "Content-Length": pdfBuffer.length });
return res.send(pdfBuffer);
```

**Comment by PejmanNik** [comment]
Can you please create a small repo/gist that helps me reproduce the issue?

**Comment by sharathm89** [comment]
@PejmanNik  here is the github repo [link](https://github.com/sharathm89/pdf-report)

you can refer to readme file to install and run

**Comment by sharathm89** [comment]
@PejmanNik  tried below code as well but the results are same. From existing repo you can run `make pdf` from api-server folder to test it.

```
const puppeteer = require("puppeteer");
const { ReportBuilder } = require("@jikji/generator");


async function build() {
	const browser = await puppeteer.launch({
		args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
		headless: "new",
	});

	try {
		await ReportBuilder.browser(browser)
			.remoteHost("http://localhost:8024")
			.report("/")
			.pdf({
				path: "./out.pdf",
			})
			.build();
	} finally {
		await browser.close();
	}
}

build();
```

**Comment by PejmanNik** [comment]
I think the issue is related to the graph transition, probably at the time of converting to PDF the bars are still hidden, try to disable this animation or use [useLayoutSuspension](https://jikji.xyz/docs/components/utilize/use-layout-suspension) to delay the print time.

![issue31](https://github.com/PejmanNik/jikji/assets/18081640/1f805315-d8b1-4a87-bbe5-64c06b8555db)

**Comment by sharathm89** [comment]
Disabling animation works..  Thanks...
