### ISSUE TITLE
How to pass jsonData in SSG?

### ISSUE THREAD

**Issue by abdul41265** [PejmanNik/jikji#33]
### Can we send dynamic data like this? And how do we access it on the front end?

 const jsonData: any = {
        title: "Test injection 💉",
        table: [
          { index: 1, caption: "data" },
          { index: 2, caption: "more data" },
        ],
      };

 await ReportBuilder.browser(browser)
  .serve("./build")
  .report("new_report")
  .jsonData(jsonData)
  .pdf({
    path: 'out.pdf'
})
  .build();

**Comment by PejmanNik** [comment]
What do you mean by dynamic data?

There is a sample in the documentation for using it:
https://jikji.xyz/docs/inject-json-data

**Comment by abdul41265** [comment]
Is this approach possible to transmit data from the server to the client side?

<img width="344" alt="Screenshot 2024-01-25 at 12 05 40 a m" src="https://github.com/PejmanNik/jikji/assets/25523671/fc50d6d5-bc9b-41e8-988f-e7463c389d3c">

**Comment by PejmanNik** [comment]
The JSON data only works when you use SSG, so there is no client. If you want to fetch the data on the client side, you need to use a normal JS/React approach, for instance, check this example: [QuoteFromAPI.tsx](https://github.com/PejmanNik/jikji/blob/e075fd56f467e8fb3693009be9964bd6402199ac/example/src/AnnualReport/QuoteFromAPI.tsx)

**Comment by abdul41265** [comment]
Is it possible to save a PDF file on the client side similar to how it's done in SSG by specifying a path?

**Comment by PejmanNik** [comment]
Please create a new issue if your question is unrelated to the original issue. I think you can find your answer in the documentation https://jikji.xyz/docs/csr-vs-ssg basically, your only option is calling `window.print()` 

Feel free to reopen the issue if you still have any questions
