### ISSUE TITLE
PDF generation in SSG is not waiting for the content to load.

### ISSUE THREAD

**Issue by abdul41265** [PejmanNik/jikji#34]
Does the current package have an option similar to "waitUntil: 'networkidle0'" in the puppeteer-report package?

`await page.goto("http://my-reports.com",{waitUntil:'networkidle0'})`

**Comment by PejmanNik** [comment]
No, but you could handle the waiting process by [LayoutSuspension](https://jikji.xyz/docs/components/utilize/use-layout-suspension)  

Also, it can be easily added to the package, you'll be welcome to create a PR for it

Here, report functions need to be modified to accept the extra options:
https://github.com/PejmanNik/jikji/blob/main/packages/generator/src/ReportBuilder.ts

and here we need to read the extra options and pass it to go to:
https://github.com/PejmanNik/jikji/blob/main/packages/generator/src/core.ts
