### ISSUE TITLE
Table Issue

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#35]
Please check the below image where table breaks in the loop and doesn't go for the next page.

Sample can be found here -> [Sandbox Link](https://codesandbox.io/p/sandbox/report-table-dom-issue-c8fm9j)

<img width="885" alt="Screenshot 2024-02-29 at 7 29 53 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/6f334afb-8a09-4bc3-9881-d47ca9e65d44">

**Comment by sharathm89** [comment]
@PejmanNik  did you find time to look into it..

**Comment by PejmanNik** [comment]
It seems to be related to your data loading mechanism. I couldn't figure out why, but in the pagination phase, the data is not yet ready. I was able to resolve your issue by postponing the pagination. However, this is a hacky solution.

```js
const TableDom = () => {
 const { release } = useLayoutSuspension('table-data');

 useEffect(() => {
  setTimeout(() => {
    release();
  }, 300);
  }, [release]);

```

**Comment by sharathm89** [comment]
Perfect it work... Thank you
