### ISSUE TITLE
React fast refresh is not compatible

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#7]
## App Component

```
const App = () => {
   return (
    <ReportRoot>
      <ReportView>

        <Section dimension={pageSize.A4}>
          <PageContent>
            <SomeView />
          </PageContent>
        </Section>

      </ReportView>
    </ReportRoot>
  );
}
```

## Table to display the list of records

```
import { Table } from "@jikji/react";

// 31 Records
const TEMP_LIST = [
  {category: "Car", subCategory: "Ford", grade: "A", bgColor: "#FF9301"},
  {category: "Truck", subCategory: "Volvo", grade: "B", bgColor: "#81C784"},
  {category: "Bike", subCategory: "Pulsur", grade: "A", bgColor: "#283593"},
  {category: "Car", subCategory: "BMW", grade: "C", bgColor: "#FF9301"},
   ...
];

const SomeView = () => {
  return (
      <Table>
        <table style={{ width: "100%"}}>
          <thead>
            <tr>
              <th scope="col" >Risk Area</th>
              <th scope="col" >Risk Sub - Area</th>
              <th scope="col">Grade</th>
            </tr>
          </thead>

          <tbody>
            {
              TEMP_LIST.map((item, index) => (
                <tr key={index}>
                  <td>{item.category}</td>
                  <td>{item.subCategory}</td>
                  <td style={{ backgroundColor: item.bgColor, textAlign: "center" }}>
                    {item.grade}</td>
                </tr>
              ))
            }
          </tbody>
        </table>
      </Table>
  );
}

export default SomeView;
```

Above code works perfectly when opened in the browser. Now when trying to convert it using **@jikji/generator**  it throws `ProtocolError: Protocol error (Page.printToPDF): Printing failed`

When the list data is more it doesn't generate the PDF.  Currently I have 31 records for which its failing.

Limiting the records to 1 page will work.

Tried even from the sample code from this [link](https://jikji.xyz/docs/components/utilize/table)

**Comment by PejmanNik** [comment]
Can you please create a repo or gist that helps me to reproduce the issue?

**Comment by sharathm89** [comment]
> Can you please create a repo or gist that helps me to reproduce the issue?

@PejmanNik  here is the sample github repo link which demonstrates cover, graph, table (issues) in it.

https://github.com/sharathm89/report-app

**Comment by PejmanNik** [comment]
could you please try it again with the last version? update to `0.3.0` and there are breaking changes in the table component (check Release note)?

also, the image in your example is bigger than A4, please change the size:
```html
      <Image
        height={'1121px'}
        width={'793px'}
        src='https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba'
      />
```

with these changes, I was able to make the pdf.
[out.pdf](https://github.com/PejmanNik/jikji/files/11928901/out.pdf)

**Comment by sharathm89** [comment]
@PejmanNik  seems to be working but now making some changes and reloading the website throws error.

Reloading the site 1 or 2 times works...

<img width="1231" alt="Screenshot 2023-07-02 at 4 38 47 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/ad7737c1-07f6-4172-aa9e-b6c1226644d1">

**Comment by PejmanNik** [comment]
Yes, it seems I used [Vite](https://vitejs.dev/) for all the test projects and it working well with it but there is a difference in RCA hot reload that cause this issue, I'll check it

**Comment by sharathm89** [comment]
> Yes, it seems I used [Vite](https://vitejs.dev/) for all the test projects and it working well with it but there is a difference in RCA hot reload that cause this issue, I'll check it

thanks... 

let me know once fixed

**Comment by PejmanNik** [comment]
I spend a lot of time on it, but unfortunately couldn't figure it out. for now please use [Vite](https://vitejs.dev/) or disable react fast refresh. I'll try to fix it.

**Comment by sharathm89** [comment]
> I spend a lot of time on it, but unfortunately couldn't figure it out. for now please use [Vite](https://vitejs.dev/) or disable react fast refresh. I'll try to fix it.

ok

**Comment by sharathm89** [comment]
I don't see this issue with new **ver 0.4.0** 

Will let you know if it occurs.
