### ISSUE TITLE
Issue when generating PDF with graph

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#9]
Tried using the below chart code it works in website and fails while generating PDF.

https://github.com/PejmanNik/jikji/blob/main/example/src/AnnualReport/Chart.tsx

```
TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded
at Timeout.<anonymous> (Users/user1/Documents/report/report-app/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:39:29)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

```

**Comment by PejmanNik** [comment]
It is because of an error in the report, you can change the puppeteer mode by setting headless to false and see the actual error. I'll try to provide more meaningful errors for generator in the next versions

**Comment by sharathm89** [comment]
> It is because of an error in the report, you can change the puppeteer mode by setting headless to false and see the actual error. I'll try to provide more meaningful errors for generator in the next versions

Thanks....
